const TRM=3357.82;
const MIN_WAGE=1750905;
const MIN_DAILY=Math.round(MIN_WAGE/30);
const WORKDAY_HOURS=8.4;
const MIN_HOUR=Math.round(MIN_DAILY/WORKDAY_HOURS);
const PRINT_PAGE=150;
const WORK_DAYS=22;
const state={view:"inicio",active:5,users:20};
const analysts=[
{id:"camilo",name:"Juan Camilo Montoya",salary:2100000,apps:"Requisiciones y cartera"},
{id:"luis",name:"Luis Grisales",salary:2100000,apps:"Auditoría logística y página general"},
{id:"juanesteban",name:"Juan Esteban Pérez",salary:2100000,apps:"Aula, trazabilidad, mesa, repositorio e inventarios"}
];
const apps=[
{id:"requisiciones",analystId:"camilo",name:"Requisición de compras",short:"Requisiciones",purpose:"Solicitudes de compra, responsables, aprobaciones, estados y trazabilidad de cada requerimiento.",reason:"Sustituye correos, archivos paralelos y aprobaciones sin ruta visible. El valor está en controlar el proceso real de compras sin pagar licencias, parametrización y soporte externo.",buildMarket:34000000,buildEi:0,ops:{hoursDay:.75,pagesDay:8,hoursEvent:0,pagesEvent:0,eventsMonth:0,reprocess:.18,realtime:.08},competitors:[{name:"Precoro",usd:499,type:"flat",source:"https://precoro.com/pricing"},{name:"Procurify",usd:1000,type:"flat",source:"https://www.procurify.com/pricing/"},{name:"Tradogram",usd:425,type:"flat",source:"https://www.tradogram.com/tradogram-procurement-2026-pricing-v2"}],impact:["Aprobaciones trazables","Menos búsquedas de correos","Responsables visibles","Consulta rápida de estados"]},
{id:"cartera",analystId:"camilo",name:"Gestión de cartera",short:"Cartera",purpose:"Seguimiento de cartera, compromisos, vencimientos, estados de cobro, responsables y control de gestión.",reason:"Ordena la gestión de cobro y reduce reprocesos por información dispersa. La compra externa implicaría licencias, configuración, campañas, soporte e integración.",buildMarket:30000000,buildEi:0,ops:{hoursDay:.8,pagesDay:4,hoursEvent:0,pagesEvent:0,eventsMonth:0,reprocess:.2,realtime:.12},competitors:[{name:"Debitia",usd:880,type:"flat",source:"https://debitia.com/"},{name:"Dapta",usd:900,type:"flat",source:"https://dapta.ai/ai-calls-register-gad-cobranzas/"},{name:"Moonflow",usd:499,type:"flat",source:"https://www.moonflow.ai/pricing"}],impact:["Seguimiento unificado","Menos pérdida de compromisos","Alertas de vencimiento","Prioridad de cartera"]},
{id:"auditoria",analystId:"luis",name:"ERP de auditoría de procesos logísticos",short:"ERP auditoría",purpose:"Auditorías logísticas, listas de verificación, evidencias, hallazgos, responsables y acciones de cierre.",reason:"Permite auditar con evidencia y seguimiento propio. El valor externo no es solo la licencia: también exige adaptar formularios, flujos, reportes y responsables.",buildMarket:34000000,buildEi:0,ops:{hoursDay:.65,pagesDay:0,hoursEvent:0,pagesEvent:35,eventsMonth:4,reprocess:.2,realtime:.15},competitors:[{name:"SafetyCulture",usd:24,type:"per_user",source:"https://safetyculture.com/pricing"},{name:"GoAudits",usd:10,type:"per_user",source:"https://goaudits.com/pricing/"},{name:"Lumiform",usd:22,type:"per_user",source:"https://lumiformapp.com/pricing/"}],impact:["Hallazgos con evidencia","Cierres trazables","Menos formatos manuales","Seguimiento de acciones"]},
{id:"paginaei",analystId:"luis",name:"Página general de Electro Ingeniería",short:"Página general EI",purpose:"Canal institucional con información general, enlaces a asesores, catálogo y puntos de consulta comercial.",reason:"Reduce consultas repetidas y ordena la entrada institucional. No compite como suite empresarial: se compara como sitio corporativo con personalización y soporte.",buildMarket:18000000,buildEi:2134000,ops:{hoursDay:.18,pagesDay:.2,hoursEvent:0,pagesEvent:0,eventsMonth:0,reprocess:.05,realtime:.1},competitors:[{name:"Wix Business Elite",usd:159,type:"flat",source:"https://www.wix.com/plans"},{name:"Webflow Business",usd:39,type:"flat",source:"https://webflow.com/pricing"},{name:"Squarespace Business",usd:23,type:"flat",source:"https://www.squarespace.com/pricing"}],impact:["Información comercial centralizada","Acceso a catálogo","Menos solicitudes repetidas","Mejor presentación institucional"]},
{id:"aula",analystId:"juanesteban",name:"Aula EI",short:"Aula EI",purpose:"Capacitaciones, módulos, evaluaciones, evidencias, certificados y seguimiento de avance.",reason:"Convierte las inducciones en contenido reutilizable. Cada jornada digitalizada evita repetir sesiones completas, impresiones y consolidación manual de evidencias.",buildMarket:26000000,buildEi:0,ops:{hoursDay:0,pagesDay:0,hoursEvent:8.4,pagesEvent:15,eventsMonth:1,reprocess:.12,realtime:.1},competitors:[{name:"TalentLMS",usd:119,type:"flat",source:"https://www.talentlms.com/prices"},{name:"LearnWorlds",usd:249,type:"flat",source:"https://www.learnworlds.com/pricing/"},{name:"MoodleCloud",usd:13.33,type:"flat",source:"https://www.moodlecloud.com/standard-plans/"}],impact:["Una jornada menos por inducción","Certificados automáticos","Evidencias centralizadas","Evaluaciones por módulo"]},
{id:"trazabilidad",analystId:"juanesteban",name:"ERP de trazabilidad logística",short:"Trazabilidad logística",purpose:"Recorrido del pedido, responsables, estados, evidencias, tiempos, reportes y alertas entre áreas.",reason:"Es la app de mayor impacto operativo. Ahorra entre una y tres horas diarias al reducir seguimiento manual por macroproceso y centralizar evidencias en tiempo real.",buildMarket:48000000,buildEi:0,ops:{hoursDay:2,pagesDay:30,hoursEvent:0,pagesEvent:0,eventsMonth:0,reprocess:.25,realtime:.15},competitors:[{name:"Quickbase Business",usd:55,type:"per_user",source:"https://www.quickbase.com/plans-and-pricing"},{name:"Odoo Custom",usd:61,type:"per_user",source:"https://www.odoo.com/pricing"},{name:"Odoo Standard",usd:31.1,type:"per_user",source:"https://www.odoo.com/pricing"}],impact:["Hasta tres horas diarias menos","30 hojas evitadas por día","Alertas y responsables visibles","Indicadores en tiempo real"]},
{id:"mesa",analystId:"juanesteban",name:"Mesa de ayuda de calidad",short:"Mesa de ayuda",purpose:"Solicitudes, radicados, responsables, tiempos, seguimiento, indicadores y trazabilidad de atención.",reason:"No se valora solo por reemplazar correos. El ahorro está en ordenar solicitudes, disminuir reprocesos, priorizar casos y medir tiempos de respuesta.",buildMarket:20000000,buildEi:0,ops:{hoursDay:.8,pagesDay:.2,hoursEvent:0,pagesEvent:0,eventsMonth:0,reprocess:.25,realtime:.15},competitors:[{name:"Zendesk Suite Team",usd:55,type:"per_user",source:"https://www.zendesk.com/pricing/"},{name:"Freshdesk Pro",usd:55,type:"per_user",source:"https://www.freshworks.com/freshdesk/pricing/"},{name:"Help Scout Plus",usd:50,type:"per_user",source:"https://www.helpscout.com/pricing/"}],impact:["Radicados y responsables","Menos solicitudes perdidas","Medición de tiempos","Menos reproceso por correo"]},
{id:"calidad",analystId:"juanesteban",name:"Página de repositorio y noticias de calidad",short:"Repositorio calidad",purpose:"Documentos, noticias, auditorías, aplicaciones e información del proceso de calidad en un solo punto.",reason:"El ahorro directo en tiempo es conservador porque su mayor aporte es facilitar acceso, transparencia y memoria documental del proceso.",buildMarket:15000000,buildEi:0,ops:{hoursDay:.25,pagesDay:.2,hoursEvent:0,pagesEvent:0,eventsMonth:0,reprocess:.1,realtime:.15},competitors:[{name:"Helpjuice",usd:249,type:"flat",source:"https://helpjuice.com/pricing"},{name:"Slab Business",usd:12.5,type:"per_user",source:"https://slab.com/pricing/"},{name:"Archbee",usd:80,type:"flat",source:"https://www.archbee.com/pricing"}],impact:["Documentos localizables","Noticias y auditorías visibles","Menos consultas repetidas","Transparencia del proceso"]},
{id:"inventario",analystId:"juanesteban",name:"APP de inventario cíclico",short:"Inventario cíclico",purpose:"Conteos físicos, evidencias, diferencias, responsables, cierres y trazabilidad de inventario.",reason:"Ahorra una hora diaria y reduce papel en conteos. Evita comprar una suite de inventario completa para resolver una necesidad puntual y controlada.",buildMarket:22000000,buildEi:0,ops:{hoursDay:1,pagesDay:2,hoursEvent:0,pagesEvent:0,eventsMonth:0,reprocess:.2,realtime:.1},competitors:[{name:"inFlow",usd:999,type:"flat",source:"https://www.inflowinventory.com/pricing"},{name:"Sortly",usd:299,type:"flat",source:"https://www.sortly.com/pricing/"},{name:"Zoho Inventory",usd:256.5,type:"flat",source:"https://www.zoho.com/inventory/pricing/"}],impact:["Una hora diaria menos","Conteos con evidencia","Cierre de diferencias","Menos digitación posterior"]}
];
const sources=[
{label:"Salario mínimo 2026 · Presidencia",url:"https://www.presidencia.gov.co/prensa/Paginas/Salario-vital-2-000-000-a-partir-de-enero-de-2026-251230.aspx"},
{label:"Jornada laboral 42 horas · MinTrabajo",url:"https://www.mintrabajo.gov.co/documents/d/guest/02ee2025410600000093441_reduccion-jornada-laboral-trabajo-suplementario-en-turnos-de-trabajo?download=true"},
{label:"Resma papel carta 500 hojas · Alkosto",url:"https://www.alkosto.com/resma-papel-tamano-carta-75g/p/7702148000043"},
{label:"Impresión blanco y negro · Imprinco",url:"https://imprinco.com/producto/impresion-color-y-negro-tinta/"},
{label:"Rendimiento tinta HP 664 · HP",url:"https://www.hp.com/co-es/shop/cartucho-de-tinta-hp-664-negra-original-f6v29al.html"}
];
const fmt=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const shortFmt=new Intl.NumberFormat("es-CO",{maximumFractionDigits:1});
const qs=s=>document.querySelector(s);
const qsa=s=>Array.from(document.querySelectorAll(s));
const el=id=>document.getElementById(id);
function money(v){return fmt.format(Math.round(v))}
function shortMoney(v){const n=Math.abs(v);if(n>=1000000000)return `$${shortFmt.format(v/1000000000)} MM`;if(n>=1000000)return `$${shortFmt.format(v/1000000)} M`;if(n>=1000)return `$${shortFmt.format(v/1000)} mil`;return money(v)}
function pct(v,max){return `${Math.max(5,Math.min(100,(v/Math.max(max,1))*100))}%`}
function analyst(id){return analysts.find(a=>a.id===id)}
function appOwner(app){return analyst(app.analystId)}
function ownedApps(id){return apps.filter(a=>a.analystId===id)}
function licenseCop(c){return (c.type==="per_user"?c.usd*state.users:c.usd)*TRM}
function compMonthly(app,c){return licenseCop(c)+app.buildMarket/12}
function marketMonthly(app){return app.competitors.reduce((s,c)=>s+compMonthly(app,c),0)/app.competitors.length}
function marketLicenseAvg(app){return app.competitors.reduce((s,c)=>s+licenseCop(c),0)/app.competitors.length}
function salaryWeight(app){const list=ownedApps(app.analystId);const total=list.reduce((s,a)=>s+marketMonthly(a),0);return total?marketMonthly(app)/total:0}
function salaryShare(app){return appOwner(app).salary*salaryWeight(app)}
function eiMonthly(app){return salaryShare(app)+app.buildEi/12}
function opSavings(app){const o=app.ops;const dailyHours=(Number(o.hoursDay)||0)*WORK_DAYS;const eventHours=(Number(o.hoursEvent)||0)*(Number(o.eventsMonth)||0);const hours=dailyHours+eventHours;const pages=(Number(o.pagesDay)||0)*WORK_DAYS+(Number(o.pagesEvent)||0)*(Number(o.eventsMonth)||0);const time=hours*MIN_HOUR;const paper=pages*PRINT_PAGE;const repro=time*(Number(o.reprocess)||0);const realtime=time*(Number(o.realtime)||0);return {hours,pages,time,paper,repro,realtime,total:time+paper+repro+realtime}}
function appCalc(app){const market=marketMonthly(app);const ei=eiMonthly(app);const ops=opSavings(app);return {market,license:marketLicenseAvg(app),buildMonthly:app.buildMarket/12,ei,salary:salaryShare(app),buildEiMonthly:app.buildEi/12,ops,avoidMarket:market-ei,totalSaving:market-ei+ops.total,roi:(market+ops.total)/Math.max(ei,1),creationSaving:app.buildMarket-app.buildEi,weight:salaryWeight(app)}}
function totals(){const market=apps.reduce((s,a)=>s+appCalc(a).market,0);const ei=apps.reduce((s,a)=>s+appCalc(a).ei,0);const ops=apps.reduce((s,a)=>s+appCalc(a).ops.total,0);const license=apps.reduce((s,a)=>s+appCalc(a).license,0);const build=apps.reduce((s,a)=>s+appCalc(a).buildMonthly,0);return {market,ei,ops,license,build,totalSaving:market-ei+ops,roi:(market+ops)/Math.max(ei,1)}}
function analystCalc(a){const list=ownedApps(a.id);const market=list.reduce((s,app)=>s+appCalc(app).market,0);const ei=list.reduce((s,app)=>s+appCalc(app).ei,0);const ops=list.reduce((s,app)=>s+appCalc(app).ops.total,0);return {list,market,ei,ops,totalSaving:market-ei+ops,roi:(market+ops)/Math.max(ei,1)}}
function load(){try{const data=JSON.parse(localStorage.getItem("eiLandingV7")||"{}");if(data.users)state.users=Number(data.users);if(Array.isArray(data.analysts))data.analysts.forEach(x=>{const a=analysts.find(y=>y.id===x.id);if(a){a.name=x.name||a.name;a.salary=Number(x.salary)||a.salary}});if(Array.isArray(data.apps))data.apps.forEach(x=>{const app=apps.find(y=>y.id===x.id);if(app){app.buildMarket=Number(x.buildMarket)||app.buildMarket;app.buildEi=Number(x.buildEi)||0;if(x.ops)Object.keys(app.ops).forEach(k=>{if(x.ops[k]!==undefined)app.ops[k]=Number(x.ops[k])})}})}catch(e){}}
function save(){localStorage.setItem("eiLandingV7",JSON.stringify({users:state.users,analysts:analysts.map(a=>({id:a.id,name:a.name,salary:a.salary})),apps:apps.map(a=>({id:a.id,buildMarket:a.buildMarket,buildEi:a.buildEi,ops:a.ops}))}))}
function setView(view){state.view=view;qsa(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`));qsa(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===view));render()}
function render(){renderHome();renderAnalysts();renderApps()}
function renderHome(){const t=totals();el("totalSaving").textContent=shortMoney(t.totalSaving);el("totalTiles").innerHTML=[['Mercado mensual',t.market],['Costo EI mensual',t.ei],['Ahorro operativo',t.ops],['Retorno',`${shortFmt.format(t.roi)}x`]].map(([k,v])=>`<article><span>${k}</span><b>${typeof v==="number"?shortMoney(v):v}</b></article>`).join("");const rows=[['Mercado externo',t.market,'fill'],['Costo interno EI',t.ei,'fill ok'],['Ahorro operativo',t.ops,'fill light'],['Ahorro total',t.totalSaving,'fill']];const max=Math.max(...rows.map(r=>r[1]));el("generalChart").innerHTML=rows.map(([label,value,cls])=>`<div class="chart-line"><label>${label}</label><div class="track"><div class="${cls}" style="--w:${pct(value,max)}"></div></div><b>${shortMoney(value)}</b></div>`).join("")}
function renderAnalysts(){el("analystCards").innerHTML=analysts.map(a=>{const c=analystCalc(a);return `<article class="analyst-card"><div class="card-row"><div><span class="tag">${c.list.length} apps</span><h3>${a.name}</h3></div><button class="mini" data-analyst-detail="${a.id}">Detalle</button></div><p>${a.apps}</p><div class="analyst-metrics"><article><span>Sueldo mensual</span><b>${shortMoney(a.salary)}</b></article><article><span>Mercado externo</span><b>${shortMoney(c.market)}</b></article><article><span>Ahorro mensual</span><b>${shortMoney(c.totalSaving)}</b></article><article><span>Retorno</span><b>${shortFmt.format(c.roi)}x</b></article></div><div class="app-pills">${c.list.map(app=>`<span>${app.short}</span>`).join("")}</div></article>`}).join("");qsa("[data-analyst-detail]").forEach(b=>b.onclick=()=>openAnalyst(b.dataset.analystDetail))}
function renderApps(){const active=apps[state.active];const owner=appOwner(active);el("appGroups").innerHTML=analysts.map(a=>`<section><p class="app-group-title">${a.name}</p>${ownedApps(a.id).map(app=>`<button class="app-chip ${apps.indexOf(app)===state.active?"active":""}" data-app="${apps.indexOf(app)}"><strong>${app.short}</strong><span>${shortMoney(appCalc(app).totalSaving)} ahorro mensual</span></button>`).join("")}</section>`).join("");qsa("[data-app]").forEach(b=>b.onclick=()=>{state.active=Number(b.dataset.app);renderApps()});el("focusOwner").textContent=owner.name;el("focusName").textContent=active.name;el("focusPurpose").textContent=active.purpose;el("focusReason").textContent=active.reason;const c=appCalc(active);el("appKpis").innerHTML=[['Mercado',c.market],['Costo EI',c.ei],['Ahorro operativo',c.ops.total],['Ahorro total',c.totalSaving]].map(([k,v])=>`<article><span>${k}</span><b>${shortMoney(v)}</b></article>`).join("");const bars=[{name:'EI interno',value:c.ei,ei:true},...active.competitors.map(comp=>({name:comp.name,value:compMonthly(active,comp)}))];const max=Math.max(...bars.map(b=>b.value));el("appChart").innerHTML=bars.map(b=>`<div class="app-bar"><label>${b.name}</label><div class="app-track"><div class="app-fill ${b.ei?"ei":""}" style="--w:${pct(b.value,max)}"></div></div><b>${shortMoney(b.value)}</b></div>`).join("")}
function rows(items){return `<table class="data-table"><tbody>${items.map(([a,b])=>`<tr><td>${a}</td><td>${b}</td></tr>`).join("")}</tbody></table>`}
function compTable(app){return `<table class="data-table"><thead><tr><th>Competencia</th><th>Licencia 20 usuarios</th><th>Creación / 12</th><th>Total mensual</th></tr></thead><tbody>${app.competitors.map(c=>`<tr><td>${c.name}</td><td>${money(licenseCop(c))}</td><td>${money(app.buildMarket/12)}</td><td>${money(compMonthly(app,c))}</td></tr>`).join("")}</tbody></table>`}
function openModal(title,tag,body){el("modalTitle").textContent=title;el("modalTag").textContent=tag;el("modalBody").innerHTML=body;el("modal").showModal()}
function openTotals(){const t=totals();const body=`<div class="kpi-row"><article><span>Mercado mensual</span><b>${shortMoney(t.market)}</b></article><article><span>Costo EI mensual</span><b>${shortMoney(t.ei)}</b></article><article><span>Ahorro operativo</span><b>${shortMoney(t.ops)}</b></article><article><span>Ahorro anual</span><b>${shortMoney(t.totalSaving*12)}</b></article></div><div class="modal-grid"><section class="detail-box"><h4>Resultado consolidado</h4>${rows([['Licencias promedio',money(t.license)],['Creación mercado mensualizada',money(t.build)],['Mercado completo',money(t.market)],['Sueldos ponderados + creación EI',money(t.ei)],['Ahorro operativo adicional',money(t.ops)],['Ahorro total mensual',money(t.totalSaving)],['Retorno general',`${shortFmt.format(t.roi)}x`]])}</section><section class="detail-box"><h4>Lectura</h4><p>El resultado muestra el costo que se evita al no comprar nueve aplicaciones externas, más el valor operativo de horas, papel, reprocesos e información en tiempo real. El costo EI se calcula con el salario de cada analista distribuido por el peso de mercado de sus apps.</p></section></div>`;openModal("Resumen económico general","Portafolio completo",body)}
function openAnalyst(id){const a=analyst(id);const c=analystCalc(a);const body=`<div class="kpi-row"><article><span>Apps</span><b>${c.list.length}</b></article><article><span>Mercado mensual</span><b>${shortMoney(c.market)}</b></article><article><span>Sueldo usado</span><b>${shortMoney(a.salary)}</b></article><article><span>Ahorro mensual</span><b>${shortMoney(c.totalSaving)}</b></article></div><div class="modal-grid"><section class="detail-box"><h4>Aplicaciones a cargo</h4><table class="data-table"><thead><tr><th>App</th><th>Costo EI</th><th>Ahorro total</th></tr></thead><tbody>${c.list.map(app=>{const x=appCalc(app);return `<tr><td>${app.short}</td><td>${money(x.ei)}</td><td>${money(x.totalSaving)}</td></tr>`}).join("")}</tbody></table></section><section class="detail-box"><h4>Control del salario</h4>${rows([['Sueldo base mensual',money(a.salary)],['Suma costo EI ponderado',money(c.ei)],['Ahorro operativo del bloque',money(c.ops)],['Retorno del bloque',`${shortFmt.format(c.roi)}x`]])}<p>La suma del salario distribuido entre las apps no supera el sueldo base del analista. La diferencia sobre el sueldo se da únicamente cuando existe creación interna mensualizada.</p></section></div>`;openModal(a.name,"Ahorro por analista",body)}
function openAppDetail(){const app=apps[state.active];const c=appCalc(app);const body=`<div class="kpi-row"><article><span>Mercado mensual</span><b>${shortMoney(c.market)}</b></article><article><span>Costo EI</span><b>${shortMoney(c.ei)}</b></article><article><span>Ahorro total</span><b>${shortMoney(c.totalSaving)}</b></article><article><span>Retorno</span><b>${shortFmt.format(c.roi)}x</b></article></div><div class="modal-grid"><section class="detail-box"><h4>Competencias</h4>${compTable(app)}</section><section class="detail-box"><h4>Valor de creación</h4>${rows([['Creación mercado estimada',money(app.buildMarket)],['Creación EI registrada',money(app.buildEi)],['Ahorro en creación',money(c.creationSaving)],['Sueldo ponderado mensual',money(c.salary)],['Peso dentro del analista',`${shortFmt.format(c.weight*100)}%`]])}</section></div><div class="modal-grid"><section class="detail-box"><h4>Aporte operativo</h4><ul>${app.impact.map(i=>`<li>${i}</li>`).join("")}</ul></section><section class="detail-box"><h4>Por qué marca valor</h4><p>${app.reason}</p></section></div>`;openModal(app.name,"Ficha completa",body)}
function openOps(){const app=apps[state.active];const c=appCalc(app);const o=c.ops;const body=`<div class="kpi-row"><article><span>Horas al mes</span><b>${shortFmt.format(o.hours)}</b></article><article><span>Hojas al mes</span><b>${shortFmt.format(o.pages)}</b></article><article><span>Valor operativo</span><b>${shortMoney(o.total)}</b></article><article><span>Jornada base</span><b>${WORKDAY_HOURS} h</b></article></div><div class="modal-grid"><section class="detail-box"><h4>Base del cálculo</h4>${rows([['Horas diarias evitadas',`${shortFmt.format(app.ops.hoursDay)} h`],['Días operativos al mes',WORK_DAYS],['Horas por evento',`${shortFmt.format(app.ops.hoursEvent)} h`],['Eventos al mes',shortFmt.format(app.ops.eventsMonth)],['Hojas diarias evitadas',shortFmt.format(app.ops.pagesDay)],['Hojas por evento',shortFmt.format(app.ops.pagesEvent)]])}</section><section class="detail-box"><h4>Valor económico</h4>${rows([['Hora salario mínimo',money(MIN_HOUR)],['Tiempo ahorrado',money(o.time)],['Papel, tinta e impresión',money(o.paper)],['Reproceso evitado',money(o.repro)],['Información en tiempo real',money(o.realtime)],['Total operativo mensual',money(o.total)]])}</section></div><section class="detail-box"><h4>Lectura operacional</h4><p>Este bloque no reemplaza el comparativo de mercado. Lo complementa con ahorros visibles dentro del proceso: menos tiempo manual, menos impresiones, menos reproceso y mejor disponibilidad de información para decisiones rápidas.</p></section>`;openModal(app.short,"Ahorro operativo",body)}
function openCompetitors(){const app=apps[state.active];openModal(app.short,"Top 3 competencias",`<section class="detail-box"><h4>Comparación con 20 usuarios</h4>${compTable(app)}<p>El total mensual incluye licencia y creación o personalización dividida en doce meses. Así se evita comparar solo el precio de una licencia contra una app interna ya configurada.</p></section>`)}
function openMethod(){const body=`<section class="formula-box"><h4>Método de cálculo</h4><p>El costo EI mensual se calcula con el salario base de cada analista y se reparte entre sus apps por peso de mercado. La aplicación con mayor valor externo recibe mayor proporción del salario. La suma mensual por analista no supera su sueldo base.</p></section><div class="method-steps"><article><b>1</b><h4>Mercado app</h4><p>Promedio del top 3 de competidores para ${state.users} usuarios + creación de mercado / 12.</p></article><article><b>2</b><h4>Peso</h4><p>Mercado de la app dividido entre el mercado total de las apps del mismo analista.</p></article><article><b>3</b><h4>Costo EI</h4><p>Sueldo mensual del analista × peso de mercado + creación EI / 12.</p></article><article><b>4</b><h4>Ahorro operativo</h4><p>Horas, papel, reproceso e información en tiempo real valorados con base conservadora.</p></article></div><div class="modal-grid"><section class="detail-box"><h4>Base laboral e impresión</h4>${rows([['Salario mínimo 2026',money(MIN_WAGE)],['Jornada usada',`${WORKDAY_HOURS} horas`],['Valor hora conservador',money(MIN_HOUR)],['Costo impresión interna',money(PRINT_PAGE)],['Días operativos mes',WORK_DAYS],['Usuarios comparados',state.users]])}</section><section class="detail-box"><h4>QA visual aplicado</h4><div class="qa-list"><article><i>✓</i><span>Información principal reducida a una app por vez</span></article><article><i>✓</i><span>Tablas largas dentro de pop-ups con scroll</span></article><article><i>✓</i><span>Textos con límites y corte visual dentro de tarjetas</span></article><article><i>✓</i><span>Diseño revisado para portátil de baja altura</span></article></div></section></div><section class="detail-box"><h4>Fuentes base</h4><div class="source-list">${sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.label}</a>`).join("")}${apps.flatMap(app=>app.competitors).map(c=>`<a href="${c.source}" target="_blank" rel="noopener">${c.name} · precio o referencia pública</a>`).join("")}</div></section>`;openModal("Base de cálculo y fuentes","Método",body)}
function openScript(kind){const data={mercado:["Qué costaría comprarlo","Cada app se compara contra tres soluciones. El valor mensual incluye licencia para 20 usuarios y creación o personalización mensualizada."],analistas:["Quién lo sostiene","El costo EI parte del salario de cada analista. No se divide por partes iguales: se pondera según el valor que reemplaza cada app."],operacion:["Qué ahorra en la operación","Se valoran horas liberadas, hojas no impresas, reprocesos evitados y disponibilidad de información en tiempo real."],hito:["Por qué marca un hito","El portafolio no es una suma de pantallas. Es conocimiento de proceso convertido en herramientas propias, sostenibles y ajustadas a Electro Ingeniería."]}[kind];openModal(data[0],"Guion de presentación",`<section class="detail-box"><h4>${data[0]}</h4><p>${data[1]}</p></section>`)}
function openEdit(){const app=apps[state.active];const a=appOwner(app);const body=`<div class="form-grid"><label>Analista<input id="editName" value="${a.name}"></label><label>Sueldo mensual<input id="editSalary" type="number" value="${a.salary}"></label><label>Creación mercado<input id="editBuildMarket" type="number" value="${app.buildMarket}"></label><label>Creación EI<input id="editBuildEi" type="number" value="${app.buildEi}"></label><label>Horas día<input id="editHoursDay" type="number" step="0.1" value="${app.ops.hoursDay}"></label><label>Hojas día<input id="editPagesDay" type="number" step="0.1" value="${app.ops.pagesDay}"></label><label>Horas evento<input id="editHoursEvent" type="number" step="0.1" value="${app.ops.hoursEvent}"></label><label>Eventos mes<input id="editEvents" type="number" step="0.1" value="${app.ops.eventsMonth}"></label><label>Hojas evento<input id="editPagesEvent" type="number" step="1" value="${app.ops.pagesEvent}"></label><label>Reproceso %<input id="editReprocess" type="number" step="0.01" value="${app.ops.reprocess}"></label></div><section class="detail-box"><h4>Edición local</h4><p>Los cambios se guardan en este navegador. El salario se redistribuye por ponderación de mercado y el valor EI mensual del analista conserva su techo salarial.</p><br><button class="primary" id="saveEdit">Guardar cambios</button></section>`;openModal(app.short,"Editar supuestos",body);el("saveEdit").onclick=()=>{a.name=el("editName").value.trim()||a.name;a.salary=Number(el("editSalary").value)||a.salary;app.buildMarket=Number(el("editBuildMarket").value)||app.buildMarket;app.buildEi=Number(el("editBuildEi").value)||0;app.ops.hoursDay=Number(el("editHoursDay").value)||0;app.ops.pagesDay=Number(el("editPagesDay").value)||0;app.ops.hoursEvent=Number(el("editHoursEvent").value)||0;app.ops.eventsMonth=Number(el("editEvents").value)||0;app.ops.pagesEvent=Number(el("editPagesEvent").value)||0;app.ops.reprocess=Number(el("editReprocess").value)||0;save();el("modal").close();render()}}
function bind(){qsa(".nav-btn").forEach(b=>b.onclick=()=>setView(b.dataset.view));el("startApps").onclick=()=>setView("apps");el("startAnalysts").onclick=()=>setView("analistas");el("methodBtn").onclick=openMethod;el("totalsBtn").onclick=openTotals;el("prevApp").onclick=()=>{state.active=(state.active-1+apps.length)%apps.length;renderApps()};el("nextApp").onclick=()=>{state.active=(state.active+1)%apps.length;renderApps()};el("competitorsBtn").onclick=openCompetitors;el("detailBtn").onclick=openAppDetail;el("opsBtn").onclick=openOps;el("editBtn").onclick=openEdit;el("closeModal").onclick=()=>el("modal").close();el("modal").addEventListener("click",e=>{if(e.target.id==="modal")el("modal").close()});qsa("[data-script]").forEach(b=>b.onclick=()=>openScript(b.dataset.script))}
load();bind();render();setTimeout(()=>el("splash").classList.add("hide"),650);
