const TRM=3357.82;
const WORK_DAYS=22;
const WORKDAY_HOURS=8.4;
const HOUR_BASE=2000000;
const HOUR_VALUE=HOUR_BASE/(WORK_DAYS*WORKDAY_HOURS);
const PRINT_COST=150;
const PAPER_COST=36;
const INK_COST=114;
const state={view:"inicio",active:5};
const analysts=[
  {id:"camilo",name:"Juan Camilo Montoya",salary:2100000,role:"Compras y cartera"},
  {id:"luis",name:"Luis Grisales",salary:2100000,role:"Auditoría logística y página general"},
  {id:"juan",name:"Juan Esteban Pérez",salary:2100000,role:"Aula, trazabilidad, mesa, repositorio e inventarios"}
];
const apps=[
  {id:"requisiciones",analystId:"camilo",name:"Requisición de compras",short:"Requisiciones",users:20,purpose:"Solicitudes de compra, aprobaciones, responsables, estados y trazabilidad de requerimientos.",reason:"No se carga papel ni tinta. El ahorro viene de ordenar solicitudes, reducir correos dispersos, evitar reprocesos y producir reportes sin consolidación manual.",marketBuild:34000000,eiBuild:13600000,processHours:10,reportHours:4,pagesMonth:0,reprocess:.12,realtime:.08,competitors:[{name:"Precoro",usd:499,type:"flat",source:"https://precoro.com/pricing"},{name:"Procurify",usd:1000,type:"flat",source:"https://www.procurify.com/pricing/"},{name:"Tradogram",usd:425,type:"flat",source:"https://www.tradogram.com/tradogram-procurement-2026-pricing-v2"}],impact:["Aprobaciones con ruta visible","Menos búsqueda en correos","Estados consultables","Responsables definidos"]},
  {id:"cartera",analystId:"camilo",name:"Gestión de cartera",short:"Cartera",users:4,purpose:"Seguimiento de cartera, compromisos, vencimientos, responsables y control de gestión.",reason:"El ahorro no está en papel. Está en disminuir seguimiento por correo, ordenar compromisos de pago, evitar pérdida de información y generar reportes de gestión.",marketBuild:30000000,eiBuild:12000000,processHours:8,reportHours:4,pagesMonth:0,reprocess:.15,realtime:.10,competitors:[{name:"Debitia",usd:880,type:"flat",source:"https://debitia.com/"},{name:"Dapta",usd:900,type:"flat",source:"https://dapta.ai/ai-calls-register-gad-cobranzas/"},{name:"Moonflow",usd:499,type:"flat",source:"https://www.moonflow.ai/pricing"}],impact:["Control de compromisos","Alertas de seguimiento","Menos cartera sin gestión","Reportes de cobro"]},
  {id:"auditoria",analystId:"luis",name:"ERP de auditoría de procesos logísticos",short:"ERP auditoría",users:8,purpose:"Auditorías logísticas, listas de verificación, evidencias, hallazgos y acciones de cierre.",reason:"Ahorra papel, tiempo de revisión y reprocesos de seguimiento. Su valor está en auditar con evidencia y cerrar hallazgos sin depender de formatos físicos.",marketBuild:34000000,eiBuild:14000000,processHours:2.5*WORK_DAYS,reportHours:4,pagesMonth:7*WORK_DAYS,reprocess:.18,realtime:.12,competitors:[{name:"SafetyCulture",usd:24,type:"per_user",source:"https://safetyculture.com/pricing"},{name:"GoAudits",usd:10,type:"per_user",source:"https://goaudits.com/pricing/"},{name:"Lumiform",usd:22,type:"per_user",source:"https://lumiformapp.com/pricing/"}],impact:["Hallazgos con evidencia","Acciones trazables","Menos papel diario","Seguimiento de cierres"]},
  {id:"paginaei",analystId:"luis",name:"Página general de Electro Ingeniería",short:"Página general EI",users:2,purpose:"Información institucional, enlaces a asesores, catálogo y entrada comercial organizada.",reason:"Tiene un ahorro especial porque la publicación no exige licenciamiento adicional. Su valor se explica por visibilidad, consulta gratuita y reducción de solicitudes repetidas.",marketBuild:18000000,eiBuild:2134000,processHours:5,reportHours:4,pagesMonth:0,reprocess:.05,realtime:.10,competitors:[{name:"Wix Business Elite",usd:159,type:"flat",source:"https://www.wix.com/plans"},{name:"Webflow Business",usd:39,type:"flat",source:"https://webflow.com/pricing"},{name:"Squarespace Business",usd:23,type:"flat",source:"https://www.squarespace.com/pricing"}],impact:["Canal institucional gratuito","Acceso a catálogo","Menos consultas repetidas","Mejor entrada comercial"]},
  {id:"aula",analystId:"juan",name:"Aula EI",short:"Aula EI",users:30,purpose:"Capacitaciones, módulos, evaluaciones, evidencias, certificados y seguimiento de avance.",reason:"Ahorra cerca de cuatro jornadas mensuales de inducción y entre 88 y 95 hojas al mes. La capacitación queda reutilizable, medible y con evidencias centralizadas.",marketBuild:26000000,eiBuild:11000000,processHours:4*WORKDAY_HOURS,reportHours:4,pagesMonth:92,reprocess:.10,realtime:.08,competitors:[{name:"TalentLMS",usd:119,type:"flat",source:"https://www.talentlms.com/prices"},{name:"LearnWorlds",usd:249,type:"flat",source:"https://www.learnworlds.com/pricing/"},{name:"MoodleCloud",usd:13.33,type:"flat",source:"https://www.moodlecloud.com/standard-plans/"}],impact:["Cuatro jornadas mensuales menos","Certificados automáticos","Evidencias centralizadas","Menos impresión de material"]},
  {id:"trazabilidad",analystId:"juan",name:"ERP de trazabilidad logística",short:"Trazabilidad logística",users:20,purpose:"Estados del pedido, responsables, evidencias, tiempos, reportes y alertas entre áreas.",reason:"Es una de las apps de mayor impacto. Ahorra entre tres y cuatro horas diarias y evita alrededor de cuarenta hojas impresas cada día.",marketBuild:56000000,eiBuild:24000000,processHours:3.5*WORK_DAYS,reportHours:4,pagesMonth:40*WORK_DAYS,reprocess:.20,realtime:.14,competitors:[{name:"Quickbase Business",usd:55,type:"per_user",source:"https://www.quickbase.com/plans-and-pricing"},{name:"Odoo Custom",usd:61,type:"per_user",source:"https://www.odoo.com/pricing"},{name:"Odoo Standard",usd:31.1,type:"per_user",source:"https://www.odoo.com/pricing"}],impact:["Hasta 3,5 horas diarias menos","40 hojas diarias evitadas","Responsables y tiempos visibles","Tableros en tiempo real"]},
  {id:"mesa",analystId:"juan",name:"Mesa de ayuda de calidad",short:"Mesa de ayuda",users:15,purpose:"Solicitudes, radicados, responsables, tiempos, seguimiento e indicadores de atención.",reason:"No se valora por papel. La ganancia está en reemplazar correos sueltos por radicados, responsables, medición de tiempos y disminución de reprocesos.",marketBuild:20000000,eiBuild:9000000,processHours:12,reportHours:4,pagesMonth:0,reprocess:.25,realtime:.14,competitors:[{name:"Zendesk Suite Team",usd:55,type:"per_user",source:"https://www.zendesk.com/pricing/"},{name:"Freshdesk Pro",usd:55,type:"per_user",source:"https://www.freshworks.com/freshdesk/pricing/"},{name:"Help Scout Plus",usd:50,type:"per_user",source:"https://www.helpscout.com/pricing/"}],impact:["Radicados consultables","Menos correos perdidos","Indicadores de atención","Priorización de solicitudes"]},
  {id:"calidad",analystId:"juan",name:"Página de repositorio y noticias de calidad",short:"Repositorio calidad",users:7,visitors:"visita transversal",purpose:"Documentos, noticias, auditorías, aplicaciones e información del proceso de calidad en un solo punto.",reason:"No se le carga papel ni tinta. Su ahorro principal es encontrar información más rápido, reducir correos de consulta y dar transparencia al proceso.",marketBuild:15000000,eiBuild:6000000,processHours:6,reportHours:4,pagesMonth:0,reprocess:.10,realtime:.12,competitors:[{name:"Helpjuice",usd:249,type:"flat",source:"https://helpjuice.com/pricing"},{name:"Slab Business",usd:12.5,type:"per_user",source:"https://slab.com/pricing/"},{name:"Archbee",usd:80,type:"flat",source:"https://www.archbee.com/pricing"}],impact:["Documentos localizables","Noticias visibles","Menos consultas repetidas","Memoria documental"]},
  {id:"inventario",analystId:"juan",name:"APP de inventario cíclico",short:"Inventario cíclico",users:5,purpose:"Conteos físicos, evidencias, diferencias, responsables, cierres y trazabilidad de inventario.",reason:"Ahorra dos horas diarias y evita cinco hojas diarias. El beneficio está en conteos más ordenados, evidencia centralizada y cierre rápido de diferencias.",marketBuild:22000000,eiBuild:9000000,processHours:2*WORK_DAYS,reportHours:4,pagesMonth:5*WORK_DAYS,reprocess:.15,realtime:.10,competitors:[{name:"inFlow",usd:999,type:"flat",source:"https://www.inflowinventory.com/pricing"},{name:"Sortly",usd:299,type:"flat",source:"https://www.sortly.com/pricing/"},{name:"Zoho Inventory",usd:256.5,type:"flat",source:"https://www.zoho.com/inventory/pricing/"}],impact:["Dos horas diarias menos","Conteos con evidencia","Menos hojas físicas","Cierre de diferencias"]}
];
const sources=[
  {label:"Salario mínimo 2026 · Presidencia",url:"https://www.presidencia.gov.co/prensa/Paginas/Salario-vital-2-000-000-a-partir-de-enero-de-2026-251230.aspx"},
  {label:"Jornada laboral 42 horas · MinTrabajo",url:"https://www.mintrabajo.gov.co/comunicados/2023/julio/los-salarios-de-las-y-los-trabajadores-se-deberan-mantener-con-la-reduccion-de-la-jornada-laboral-en-colombia"},
  {label:"Papel carta 500 hojas · MercadoLibre",url:"https://listado.mercadolibre.com.co/resma-papel-tamano-carta"},
  {label:"Impresión blanco y negro · Imprinco",url:"https://imprinco.com/producto/impresion-color-y-negro-tinta/"},
  {label:"Fotocopias desde $90 · Imprinco",url:"https://imprinco.com/producto/fotocopias-negro-y-color/"}
];
const fmt=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const nf=new Intl.NumberFormat("es-CO",{maximumFractionDigits:1});
const qs=s=>document.querySelector(s);
const qsa=s=>Array.from(document.querySelectorAll(s));
const money=v=>fmt.format(Math.round(v));
const compact=v=>{const n=Math.abs(v);if(n>=1000000000)return `$${nf.format(v/1000000000)} MM`;if(n>=1000000)return `$${nf.format(v/1000000)} M`;if(n>=1000)return `$${nf.format(v/1000)} mil`;return money(v)};
const analystById=id=>analysts.find(a=>a.id===id);
function competitorMonthly(app,c){return (c.type==="per_user"?c.usd*app.users:c.usd)*TRM}
function licenseAvg(app){return app.competitors.reduce((s,c)=>s+competitorMonthly(app,c),0)/app.competitors.length}
function timeSaving(app){return (app.processHours+app.reportHours)*HOUR_VALUE}
function printSaving(app){return app.pagesMonth*PRINT_COST}
function reprocessSaving(app){return timeSaving(app)*app.reprocess}
function realtimeSaving(app){return timeSaving(app)*app.realtime}
function operationalSaving(app){return timeSaving(app)+printSaving(app)+reprocessSaving(app)+realtimeSaving(app)}
function marketMonthly(app){return licenseAvg(app)+(app.marketBuild/12)}
function appGroup(analystId){return apps.filter(a=>a.analystId===analystId)}
function totalMarketByAnalyst(analystId){return appGroup(analystId).reduce((s,a)=>s+marketMonthly(a),0)}
function eiCost(app){const analyst=analystById(app.analystId);const total=totalMarketByAnalyst(app.analystId);return total?analyst.salary*(marketMonthly(app)/total):0}
function appNet(app){return marketMonthly(app)+operationalSaving(app)-eiCost(app)}
function appAnnual(app){return appNet(app)*12}
function analystTotals(analyst){const group=appGroup(analyst.id);const market=group.reduce((s,a)=>s+marketMonthly(a),0);const ops=group.reduce((s,a)=>s+operationalSaving(a),0);return{apps:group.length,market,ops,salary:analyst.salary,net:market+ops-analyst.salary,annual:(market+ops-analyst.salary)*12}}
function portfolio(){const market=apps.reduce((s,a)=>s+marketMonthly(a),0);const ops=apps.reduce((s,a)=>s+operationalSaving(a),0);const salary=analysts.reduce((s,a)=>s+a.salary,0);return{market,ops,salary,net:market+ops-salary,annual:(market+ops-salary)*12}}
let charts={};
function destroyChart(id){if(charts[id]){charts[id].destroy();charts[id]=null}}
function makeChart(id,type,data,options={}){destroyChart(id);const ctx=document.getElementById(id);if(!ctx||!window.Chart)return;charts[id]=new Chart(ctx,{type,data,options:{responsive:true,maintainAspectRatio:false,animation:{duration:750,easing:"easeOutQuart"},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.dataset.label||c.label}: ${money(c.raw)}`}}},scales:type==="bar"?{x:{ticks:{callback:v=>compact(v)},grid:{color:"#edf5fc"}},y:{grid:{display:false},ticks:{font:{size:11,weight:"700"}}}}:{},...options}})}
function setView(view){state.view=view;qsa(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`));qsa(".nav-btn[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));if(view==="inicio")renderOverviewCharts();if(view==="analistas")renderAnalysts();if(view==="apps")renderActiveApp()}
function renderSummary(){const p=portfolio();qs("#totalMarket").textContent=money(p.market);qs("#totalSalary").textContent=money(p.salary);qs("#totalNet").textContent=money(p.net)}
function renderOverviewCharts(){makeChart("appSavingsChart","bar",{labels:apps.map(a=>a.short),datasets:[{label:"Ahorro neto mensual",data:apps.map(a=>appNet(a)),backgroundColor:apps.map(a=>a.id===apps[state.active].id?"#126cbd":"#8dc9ff"),borderRadius:12,borderSkipped:false}]},{indexAxis:"y",scales:{x:{ticks:{callback:v=>compact(v)},grid:{color:"#edf5fc"}},y:{grid:{display:false},ticks:{font:{size:11,weight:"700"}}}}});const totals=analysts.map(analystTotals);makeChart("analystChart","doughnut",{labels:analysts.map(a=>a.name.split(" ").slice(0,2).join(" ")),datasets:[{data:totals.map(t=>t.net),backgroundColor:["#0b4f92","#1685e5","#6fbfff"],borderWidth:0}]},{cutout:"64%",plugins:{legend:{display:true,position:"bottom",labels:{boxWidth:10,font:{size:11,weight:"700"}}},tooltip:{callbacks:{label:c=>`${c.label}: ${money(c.raw)}`}}}})}
function renderAnalysts(){const board=qs("#analystBoard");board.innerHTML=analysts.map(a=>{const t=analystTotals(a);const group=appGroup(a.id);return `<article class="analyst-card card"><header><div><span class="eyebrow">${a.role}</span><h3>${a.name}</h3></div><span class="badge">${t.apps} apps</span></header><div class="analyst-metrics"><div class="small-metric"><span>Mercado mensual</span><b>${money(t.market)}</b></div><div class="small-metric"><span>Sueldo mensual</span><b>${money(t.salary)}</b></div><div class="small-metric"><span>Ahorro operativo</span><b>${money(t.ops)}</b></div><div class="small-metric green"><span>Neto mensual</span><b>${money(t.net)}</b></div></div><div class="pill-list">${group.map(app=>`<button data-app-jump="${app.id}">${app.short}</button>`).join("")}</div></article>`}).join("");qsa("[data-app-jump]").forEach(b=>b.addEventListener("click",()=>{state.active=apps.findIndex(a=>a.id===b.dataset.appJump);setView("apps")}))}
function renderAppList(){const list=qs("#appList");list.innerHTML=apps.map((app,i)=>`<button class="app-item ${i===state.active?"active":""}" data-app-index="${i}"><strong>${app.short}</strong><span>${analystById(app.analystId).name} · ${app.users} usuarios</span></button>`).join("");qsa("[data-app-index]").forEach(b=>b.addEventListener("click",()=>{state.active=Number(b.dataset.appIndex);renderActiveApp()}))}
function renderActiveApp(){renderAppList();const app=apps[state.active];const analyst=analystById(app.analystId);qs("#activeOwner").textContent=`${analyst.name} · ${app.users} usuarios${app.visitors?` · ${app.visitors}`:""}`;qs("#activeTitle").textContent=app.name;qs("#activePurpose").textContent=app.purpose;qs("#activeUsers").textContent=`${app.users} usuarios base`;qs("#activeReason").textContent=app.reason;qs("#activeKpis").innerHTML=`<article class="kpi"><span>Mercado mensual</span><b>${money(marketMonthly(app))}</b></article><article class="kpi"><span>Costo EI asignado</span><b>${money(eiCost(app))}</b></article><article class="kpi"><span>Ahorro operativo</span><b>${money(operationalSaving(app))}</b></article><article class="kpi green"><span>Neto mensual</span><b>${money(appNet(app))}</b></article>`;makeChart("activeAppChart","bar",{labels:["Mercado equivalente","Costo EI","Ahorro operativo","Neto mensual"],datasets:[{label:"Valor mensual",data:[marketMonthly(app),eiCost(app),operationalSaving(app),appNet(app)],backgroundColor:["#126cbd","#8dc9ff","#0c9b72","#08315f"],borderRadius:14,borderSkipped:false}]},{indexAxis:"y",plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money(c.raw)}}},scales:{x:{ticks:{callback:v=>compact(v)},grid:{color:"#edf5fc"}},y:{grid:{display:false},ticks:{font:{size:12,weight:"800"}}}}})}
function renderDetail(){const app=apps[state.active];const analyst=analystById(app.analystId);qs("#detailTitle").textContent=app.name;qs("#detailBody").innerHTML=`<section class="detail-grid"><article class="detail-card"><span>Analista</span><b>${analyst.name}</b></article><article class="detail-card"><span>Usuarios</span><b>${app.users}</b></article><article class="detail-card"><span>Valor EI creación</span><b>${money(app.eiBuild)}</b></article><article class="detail-card green"><span>Ahorro anual</span><b>${money(appAnnual(app))}</b></article></section><section class="two-col"><article class="box"><h4>Qué aporta</h4><p>${app.reason}</p></article><article class="box"><h4>Impactos visibles</h4><ul>${app.impact.map(i=>`<li>${i}</li>`).join("")}</ul></article></section><section class="box"><h4>Lectura económica</h4><p>Comprar una solución equivalente exigiría licencia, implementación, parametrización y soporte. En EI el costo mensual se toma del sueldo del analista responsable y se pondera por el peso de mercado de sus apps. Por eso el costo interno se mantiene bajo control y el ahorro se explica sin inflar papel, horas ni licencias.</p></section><section class="detail-grid"><article class="detail-card"><span>Licencia promedio</span><b>${money(licenseAvg(app))}</b></article><article class="detail-card"><span>Creación mercado</span><b>${money(app.marketBuild)}</b></article><article class="detail-card"><span>Creación ahorrada</span><b>${money(app.marketBuild-app.eiBuild)}</b></article><article class="detail-card"><span>Retorno mensual</span><b>${nf.format((marketMonthly(app)+operationalSaving(app))/eiCost(app))}x</b></article></section>`}
function renderCompetition(){const app=apps[state.active];qs("#competitionTitle").textContent=`Top 3 competencia · ${app.short}`;const labels=app.competitors.map(c=>c.name);const values=app.competitors.map(c=>competitorMonthly(app,c));makeChart("competitionChart","bar",{labels,datasets:[{label:"Licencia mensual para usuarios aplicables",data:values,backgroundColor:["#08315f","#126cbd","#8dc9ff"],borderRadius:14,borderSkipped:false}]},{indexAxis:"y",plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money(c.raw)}}},scales:{x:{ticks:{callback:v=>compact(v)},grid:{color:"#edf5fc"}},y:{grid:{display:false},ticks:{font:{size:12,weight:"800"}}}}});qs("#competitionTable").innerHTML=`<table class="data-table"><thead><tr><th>Competencia</th><th>Base</th><th>Valor mensual COP</th></tr></thead><tbody>${app.competitors.map(c=>`<tr><td><a href="${c.source}" target="_blank" rel="noreferrer">${c.name}</a></td><td>${c.type==="per_user"?`${app.users} usuarios × USD ${c.usd}`:`Plan publicado USD ${c.usd}`}</td><td>${money(competitorMonthly(app,c))}</td></tr>`).join("")}</tbody></table>`}
function renderSaving(){const app=apps[state.active];qs("#savingTitle").textContent=`Ahorro operativo · ${app.short}`;const time=timeSaving(app);const print=printSaving(app);const repro=reprocessSaving(app);const real=realtimeSaving(app);makeChart("savingChart","bar",{labels:["Horas proceso", "Informes incluidos", "Papel y tinta", "Reprocesos", "Tiempo real"],datasets:[{label:"Ahorro mensual",data:[app.processHours*HOUR_VALUE,app.reportHours*HOUR_VALUE,print,repro,real],backgroundColor:["#08315f","#126cbd","#8dc9ff","#0c9b72","#82d8be"],borderRadius:14,borderSkipped:false}]},{indexAxis:"y",plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money(c.raw)}}},scales:{x:{ticks:{callback:v=>compact(v)},grid:{color:"#edf5fc"}},y:{grid:{display:false},ticks:{font:{size:12,weight:"800"}}}}});qs("#savingBreakdown").innerHTML=`<div class="saving-table"><table class="data-table"><thead><tr><th>Concepto</th><th>Base mensual</th><th>Valor</th></tr></thead><tbody><tr><td>Horas de proceso, correo o jornada operativa</td><td>${nf.format(app.processHours)} h × ${money(HOUR_VALUE)}</td><td>${money(app.processHours*HOUR_VALUE)}</td></tr><tr><td>Horas adicionales por informes</td><td>${nf.format(app.reportHours)} h × ${money(HOUR_VALUE)}</td><td>${money(app.reportHours*HOUR_VALUE)}</td></tr><tr><td>Papel, tinta e impresión</td><td>${nf.format(app.pagesMonth)} hojas × ${money(PRINT_COST)}</td><td>${money(print)}</td></tr><tr><td>Reprocesos evitados</td><td>${nf.format(app.reprocess*100)}% del valor de tiempo</td><td>${money(repro)}</td></tr><tr><td>Información en tiempo real y tableros</td><td>${nf.format(app.realtime*100)}% del valor de tiempo</td><td>${money(real)}</td></tr><tr><td><strong>Total ahorro operativo</strong></td><td></td><td><strong>${money(operationalSaving(app))}</strong></td></tr></tbody></table></div>`}
function renderMethod(){qs("#methodBody").innerHTML=`<section class="method-grid"><div class="formula"><b>1. Costo de mercado mensual equivalente</b><code>Promedio mensual de competencia para usuarios aplicables + costo de creación externa / 12</code><b>2. Costo EI mensual por app</b><code>Sueldo del analista × peso de mercado de la app dentro de su grupo</code><b>3. Peso de mercado</b><code>Mercado mensual equivalente de la app / mercado mensual total de apps del mismo analista</code><b>4. Ahorro operativo</b><code>Horas ahorradas × salario hora + hojas × impresión + reprocesos + información en tiempo real</code></div><div class="formula"><b>Bases usadas</b><code>Salario analista: $2.100.000 mensual</code><code>Valor hora operativa: $2.000.000 / 22 días / 8,4 horas = ${money(HOUR_VALUE)}</code><code>Impresión estimada: hoja $${PAPER_COST} + tinta/toner $${INK_COST} = ${money(PRINT_COST)}</code><code>Días laborales de referencia: ${WORK_DAYS} días al mes</code></div></section><section class="qa-grid"><article>Solo Aula EI, Trazabilidad, ERP auditoría e Inventario tienen papel y tinta.</article><article>Requisiciones, Cartera, Mesa, Página EI y Repositorio se valoran por correos, búsqueda, reportes y reprocesos.</article><article>La suma del costo mensual por analista nunca supera su sueldo base.</article></section><section class="box"><h4>Fuentes y referencias</h4><div class="source-grid">${sources.map(s=>`<a href="${s.url}" target="_blank" rel="noreferrer">${s.label}</a>`).join("")}</div></section>`}
function openModal(kind){if(kind==="detalle"){renderDetail();qs("#modalDetalle").showModal()}if(kind==="competencia"){qs("#modalCompetencia").showModal();setTimeout(renderCompetition,40)}if(kind==="ahorro"){qs("#modalAhorro").showModal();setTimeout(renderSaving,40)}if(kind==="metodo"){renderMethod();qs("#modalMetodo").showModal()}}
function bind(){qsa("[data-view]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));qsa("[data-view-go]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.viewGo)));qsa("[data-modal]").forEach(b=>b.addEventListener("click",()=>openModal(b.dataset.modal)));qsa("[data-close]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));qsa("dialog").forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));qs("#prevApp").addEventListener("click",()=>{state.active=(state.active-1+apps.length)%apps.length;renderActiveApp()});qs("#nextApp").addEventListener("click",()=>{state.active=(state.active+1)%apps.length;renderActiveApp()})}
function boot(){bind();renderSummary();renderAppList();renderAnalysts();renderActiveApp();renderOverviewCharts()}
window.addEventListener("load",boot);
